"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&=sfh^@7onsmh0^!$ugl(nytux_&(nxv^rxbcso85cavjo&t$a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'records',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'accounts.User'

UNFOLD = {
    'SITE_TITLE': 'JRMSU REGISTRAR MANAGEMENT SYSTEM',
    'SITE_HEADER': 'JRMSU-KC REGISTRAR ',
    'SITE_SUBHEADER': 'MANAGEMENT SYSTEM',
    'SITE_ICON': '/static/admin/img/jrmsu-logo.svg',
    'SITE_FAVICONS': [
        {
            'href': '/static/admin/img/jrmsu-logo.svg',
            'rel': 'icon',
            'type': 'image/svg+xml',
        },
    ],
    'SITE_SYMBOL': 'inventory_2',
    'SITE_URL': '/admin/',
    'SITE_DROPDOWN': [
        {
            'title': 'Admin dashboard',
            'icon': 'dashboard',
            'link': '/admin/',
        },
        {
            'title': 'Accounts API',
            'icon': 'api',
            'link': '/api/accounts/',
        },
    ],
    'SHOW_BACK_BUTTON': True,
    'SHOW_VIEW_ON_SITE': False,
    'ENVIRONMENT': 'config.unfold.environment_callback',
    'ENVIRONMENT_TITLE_PREFIX': '[local]',
    'DASHBOARD_CALLBACK': 'config.unfold.dashboard_callback',
    'COLORS': {
        'primary': {
            '50': '#effefb',
            '100': '#ccfbf1',
            '200': '#99f6e4',
            '300': '#5eead4',
            '400': '#2dd4bf',
            '500': '#14b8a6',
            '600': '#0d9488',
            '700': '#0f766e',
            '800': '#115e59',
            '900': '#134e4a',
            '950': '#042f2e',
        },
    },
    'COMMAND': {
        'search_models': [
            'records.college',
            'records.course',
            'records.student',
            'records.studentdocument',
            'accounts.user',
            'admin.logentry',
        ],
        'show_history': True,
    },
    'ACCOUNT': {
        'navigation': [
            {
                'title': 'My profile',
                'link': 'config.unfold.profile_link',
            },
            {
                'title': 'Change password',
                'link': '/admin/password_change/',
            },
        ],
    },
    'SIDEBAR': {
        'show_search': False,
        'command_search': False,
        'show_all_applications': True,
        'navigation': [
            {
                'title': 'Dashboard',
                'collapsible': False,
                'items': [
                    {
                        'title': 'Overall Dashboard',
                        'icon': 'dashboard',
                        'link': '/admin/',
                    },
                ],
            },
            {
                'title': 'Student Records',
                'separator': True,
                'collapsible': False,
                'items': [
                    {
                        'title': 'Colleges',
                        'icon': 'account_balance',
                        'link': '/admin/records/college/',
                        'badge': 'config.unfold.colleges_badge',
                    },
                    {
                        'title': 'Courses',
                        'icon': 'menu_book',
                        'link': '/admin/records/course/',
                        'badge': 'config.unfold.courses_badge',
                    },
                    {
                        'title': 'Students',
                        'icon': 'school',
                        'link': '/admin/records/student/',
                        'badge': 'config.unfold.students_badge',
                    },
                    {
                        'title': 'Archived Documents',
                        'icon': 'folder_copy',
                        'link': '/admin/records/studentdocument/',
                        'badge': 'config.unfold.documents_badge',
                    },
                ],
            },
            {
                'title': 'Accounts',
                'separator': True,
                'collapsible': False,
                'items': [
                    {
                        'title': 'Users',
                        'icon': 'person',
                        'link': '/admin/accounts/user/',
                        'badge': 'config.unfold.active_users_badge',
                    },
                ],
            },
            {
                'title': 'API',
                'separator': True,
                'items': [
                    {
                        'title': 'Accounts endpoint',
                        'icon': 'api',
                        'link': '/api/accounts/',
                    },
                ],
            },
            {
                'title': 'System',
                'separator': True,
                'items': [
                    {
                        'title': 'Activity Log',
                        'icon': 'history',
                        'link': '/admin/admin/logentry/',
                    },
                ],
            },
        ],
    },
    'TABS': [
        {
            'models': ['records.college'],
            'items': [
                {
                    'title': 'All colleges',
                    'link': '/admin/records/college/',
                },
                {
                    'title': 'Active',
                    'link': '/admin/records/college/?is_active__exact=1',
                },
                {
                    'title': 'Inactive',
                    'link': '/admin/records/college/?is_active__exact=0',
                },
            ],
        },
        {
            'models': ['records.course'],
            'items': [
                {
                    'title': 'All courses',
                    'link': '/admin/records/course/',
                },
                {
                    'title': 'Active',
                    'link': '/admin/records/course/?is_active__exact=1',
                },
                {
                    'title': 'Inactive',
                    'link': '/admin/records/course/?is_active__exact=0',
                },
            ],
        },
        {
            'models': ['records.student'],
            'items': [
                {
                    'title': 'All students',
                    'link': '/admin/records/student/',
                },
                {
                    'title': 'Active',
                    'link': '/admin/records/student/?status__exact=active',
                },
                {
                    'title': 'Archived',
                    'link': '/admin/records/student/?status__exact=archived',
                },
            ],
        },
        {
            'models': ['records.studentdocument'],
            'items': [
                {
                    'title': 'All documents',
                    'link': '/admin/records/studentdocument/',
                },
                {
                    'title': 'Transcripts',
                    'link': '/admin/records/studentdocument/?document_type__exact=transcript',
                },
                {
                    'title': 'Birth certificates',
                    'link': '/admin/records/studentdocument/?document_type__exact=birth_certificate',
                },
            ],
        },
        {
            'models': ['accounts.user'],
            'items': [
                {
                    'title': 'All users',
                    'link': '/admin/accounts/user/',
                },
                {
                    'title': 'Active',
                    'link': '/admin/accounts/user/?is_active__exact=1',
                },
                {
                    'title': 'Superusers',
                    'link': '/admin/accounts/user/?is_superuser__exact=1',
                },
            ],
        },
        {
            'models': ['admin.logentry'],
            'items': [
                {
                    'title': 'All activity',
                    'link': '/admin/admin/logentry/',
                },
                {
                    'title': 'Added',
                    'link': '/admin/admin/logentry/?action_flag__exact=1',
                },
                {
                    'title': 'Updated',
                    'link': '/admin/admin/logentry/?action_flag__exact=2',
                },
                {
                    'title': 'Deleted',
                    'link': '/admin/admin/logentry/?action_flag__exact=3',
                },
            ],
        },
    ],
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
