# Generated by Django 6.0.4 on 2026-05-16 15:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import records.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('suffix', models.CharField(blank=True, max_length=30)),
                ('program', models.CharField(blank=True, max_length=150)),
                ('year_level', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name', 'student_number'),
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('admission', 'Admission'), ('transcript', 'Transcript of Records'), ('grades', 'Grades'), ('birth_certificate', 'Birth Certificate'), ('good_moral', 'Good Moral'), ('diploma', 'Diploma'), ('request_form', 'Request Form'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(upload_to=records.models.student_document_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp'])])),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('received_at', models.DateField(default=django.utils.timezone.localdate)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_student_documents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='records.student')),
            ],
            options={
                'ordering': ('student__last_name', 'student__first_name', '-received_at', 'title'),
            },
        ),
    ]
