# Generated by Django 6.0.4 on 2026-05-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(blank=True, max_length=150, verbose_name='course'),
        ),
    ]
