# Generated by Django 6.0.4 on 2026-05-16 15:54

import django.db.models.deletion
from django.db import migrations, models


def create_courses_from_existing_student_programs(apps, schema_editor):
    Course = apps.get_model('records', 'Course')
    Student = apps.get_model('records', 'Student')

    for student in Student.objects.filter(course__isnull=True).exclude(program='').iterator():
        program = student.program.strip()
        college = student.college.strip() or 'Unassigned'

        if not program:
            continue

        course, _ = Course.objects.get_or_create(
            college=college,
            name=program,
            defaults={
                'code': program[:30],
                'years': 4,
            },
        )
        student.course = course
        student.save(update_fields=['course'])


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_student_college_alter_student_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(blank=True, max_length=150, verbose_name='legacy course name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_level',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=30)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('college', models.CharField(db_index=True, max_length=150)),
                ('years', models.PositiveSmallIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('college', 'code', 'name'),
                'indexes': [models.Index(fields=['college', 'name'], name='records_cou_college_575a08_idx'), models.Index(fields=['college', 'code'], name='records_cou_college_83675b_idx')],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='records.course'),
        ),
        migrations.RunPython(
            create_courses_from_existing_student_programs,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['course', 'year_level'], name='records_stu_course__8abd93_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status', 'year_level'], name='records_stu_status_98947c_idx'),
        ),
    ]
