# Generated by Django 6.0.4 on 2026-05-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_student_college_alter_student_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='degree_type',
            field=models.CharField(choices=[('BS', 'BS'), ('BA', 'BA')], db_index=True, default='BS', max_length=2, verbose_name='degree template'),
        ),
    ]
